package main

import (
	"regexp"
	"testing"
)

var uuidv4Pattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

func TestControlPlaneHeadersCarryFullIdentitySet(t *testing.T) {
	h := buildControlPlaneHeaders("")
	checks := map[string]string{
		"HTTP-Referer":        identityRefererOrigin,
		"User-Agent":          "ZCode/" + zcodeClientVersion,
		"X-ZCode-App-Version": zcodeClientVersion,
		"X-Title":             "Z Code@" + identitySourceTitle,
		"X-ZCode-Agent":       "glm",
		"X-Platform":          identityPlatform + "-" + identityArch,
		"X-Release-Channel":   identityReleaseChannel,
		"X-Client-Language":   identityClientLanguage,
		"X-Client-Timezone":   identityClientTimezone,
		"X-Os-Category":       identityOSCategory,
		"X-Os-Version":        identityOSVersion,
	}
	for key, want := range checks {
		if got := h.Get(key); got != want {
			t.Errorf("header %s=%q, want %q", key, got, want)
		}
	}
	if got := h.Get("X-Device-Mid"); got != "" {
		t.Fatalf("X-Device-Mid must be omitted when deviceMid is empty, got %q", got)
	}
	if got := h.Get("Authorization"); got != "" {
		t.Fatalf("control-plane set must not carry credentials, got %q", got)
	}
}

func TestControlPlaneHeadersIncludeDeviceMIDWhenProvided(t *testing.T) {
	h := buildControlPlaneHeaders("11111111-2222-4333-8444-555555555555")
	if got := h.Get("X-Device-Mid"); got != "11111111-2222-4333-8444-555555555555" {
		t.Fatalf("X-Device-Mid=%q", got)
	}
}

func TestBuildZCodeIdentityHeadersPreservesCredentials(t *testing.T) {
	h, mid := buildZCodeIdentityHeaders(authStorage{
		ZCodeJWTToken:       "jwt-token",
		CaptchaVerifyParam:  "verify-param",
		CaptchaVerifyRegion: "sgp",
		DeviceMID:           "mid-0001",
	})
	if got := h.Get("Authorization"); got != "Bearer jwt-token" {
		t.Fatalf("Authorization=%q", got)
	}
	if got := h.Get("X-Aliyun-Captcha-Verify-Param"); got != "verify-param" {
		t.Fatalf("captcha param=%q", got)
	}
	if got := h.Get("X-Aliyun-Captcha-Verify-Region"); got != "sgp" {
		t.Fatalf("captcha region=%q", got)
	}
	if got := h.Get("Content-Type"); got != "application/json" {
		t.Fatalf("Content-Type=%q", got)
	}
	if got := h.Get("anthropic-version"); got != "2023-06-01" {
		t.Fatalf("anthropic-version=%q", got)
	}
	if got := h.Get("x-api-key"); got != "" {
		t.Fatalf("x-api-key must not carry a Coding Plan JWT: %q", got)
	}
	if got := h.Get("X-Device-Mid"); got != "mid-0001" {
		t.Fatalf("X-Device-Mid must reuse the persisted value, got %q", got)
	}
	if mid != "mid-0001" {
		t.Fatalf("resolved mid=%q", mid)
	}
}

func TestDeviceMIDAutoGeneratedAndReusedWhenMissing(t *testing.T) {
	generatedDeviceMID.Lock()
	generatedDeviceMID.value = ""
	generatedDeviceMID.Unlock()

	first := resolveDeviceMID(authStorage{ZCodeJWTToken: "jwt"})
	second := resolveDeviceMID(authStorage{ZCodeJWTToken: "jwt"})
	if first == "" || !uuidv4Pattern.MatchString(first) {
		t.Fatalf("auto-generated device_mid is not a UUIDv4: %q", first)
	}
	if first != second {
		t.Fatalf("auto-generated device_mid must be stable per process: %q vs %q", first, second)
	}
	h, mid := buildZCodeIdentityHeaders(authStorage{ZCodeJWTToken: "jwt"})
	if mid != first || h.Get("X-Device-Mid") != first {
		t.Fatalf("header mid=%q resolved mid=%q, want %q", h.Get("X-Device-Mid"), mid, first)
	}
}

func TestDeviceMIDRejectsHeaderInjection(t *testing.T) {
	generatedDeviceMID.Lock()
	generatedDeviceMID.value = ""
	generatedDeviceMID.Unlock()

	// CRLF injection attempts must be ignored and replaced with a safe MID.
	for _, evil := range []string{"mid\r\nX-Evil: 1", "mid\nInjected: yes", "mid\x00null"} {
		mid := resolveDeviceMID(authStorage{DeviceMID: evil})
		if !uuidv4Pattern.MatchString(mid) {
			t.Fatalf("unsafe device_mid %q was not sanitized: %q", evil, mid)
		}
	}
}

func TestNewDeviceMIDFormat(t *testing.T) {
	for i := 0; i < 16; i++ {
		mid := newDeviceMID()
		if !uuidv4Pattern.MatchString(mid) {
			t.Fatalf("newDeviceMID()=%q is not a valid UUIDv4", mid)
		}
	}
}
